export const puppyList = [
  {
    id: 1,
    name: "Sherlock Bones",
    email: "Sherlock@email.com",
    isCute: true,
    age: 7,
    ownerId: 1,
    tricks: [
      { id: 2, title: "Roll Over" },
      {
        id: 3,
        title:
          "Investigating cases of food droped on floors, and squirrels in the yard",
      },
    ],
  },
  {
    id: 2,
    name: "Porkchop",
    email: "piggy@email.com",
    isCute: true,
    age: 3,
    ownerId: 1,
    tricks: [{ id: 1, title: "Stay and Come" }],
  },
  {
    id: 3,
    name: "Dobbie",
    email: "Dobs@email.com",
    isCute: true,
    age: 2,
    ownerId: 2,
    tricks: [{ id: 1, title: "Speak" }],
  },
  {
    id: 4,
    name: "Sergeant Barkowitz",
    email: "the-sarge@email.com",
    isCute: true,
    age: 4,
    ownerId: 2,
    tricks: [{ id: 2, title: "Lay Down" }],
  },
  {
    id: 5,
    name: "Winnie the Pooch",
    email: "winnie@email.com",
    isCute: true,
    age: 7,
    ownerId: 3,
    tricks: [],
  },
  {
    id: 6,
    name: "Miss Furbulous",
    email: "miss-furby@email.com",
    isCute: true,
    age: 9,
    ownerId: 3,
    tricks: [],
  },
  {
    id: 7,
    name: "Taco Bella",
    email: "Tbella@email.com",
    isCute: true,
    age: 2,
    ownerId: 3,
    tricks: [{ id: 1, title: "Jump" }],
  },
];
